import { Card, CardContent, CardHeader, CardTitle } from "@/components/molecules/card"
import { Badge } from "@/components/atoms/badge"
import { FileText, TrendingUp, Target, Zap } from "lucide-react"

interface AIReportsProps {
  className?: string
}

export function AIReportsSection({ className }: AIReportsProps) {
  const reports = [
    {
      icon: FileText,
      title: "Market Analysis",
      description: "Comprehensive analysis of talent market trends and opportunities",
      status: "Updated",
      priority: "high",
    },
    {
      icon: TrendingUp,
      title: "Performance Insights",
      description: "AI-powered insights into athlete performance metrics and predictions",
      status: "New",
      priority: "medium",
    },
    {
      icon: Target,
      title: "Opportunity Matching",
      description: "Intelligent matching between athletes and sponsorship opportunities",
      status: "Draft",
      priority: "high",
    },
    {
      icon: Zap,
      title: "Trend Predictions",
      description: "Advanced predictions for upcoming sports industry trends",
      status: "In Progress",
      priority: "low",
    },
  ]

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "high":
        return "bg-red-100 text-red-800"
      case "medium":
        return "bg-yellow-100 text-yellow-800"
      case "low":
        return "bg-blue-100 text-blue-800"
      default:
        return "bg-gray-100 text-gray-800"
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case "Updated":
        return "bg-green-100 text-green-800"
      case "New":
        return "bg-blue-100 text-blue-800"
      case "Draft":
        return "bg-yellow-100 text-yellow-800"
      case "In Progress":
        return "bg-orange-100 text-orange-800"
      default:
        return "bg-gray-100 text-gray-800"
    }
  }

  return (
    <div className={className}>
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">AI Reports & Analytics</h2>
        <p className="text-gray-600">
          Discover intelligent insights powered by advanced AI analysis to help you make informed decisions
          in the sports industry.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reports.map((report, index) => {
          const IconComponent = report.icon
          return (
            <Card
              key={index}
              className="group hover:shadow-lg transition-all duration-300 cursor-pointer border-gray-200 hover:border-gray-300"
            >
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <div className="p-2 bg-blue-50 rounded-lg group-hover:bg-blue-100 transition-colors">
                      <IconComponent className="h-5 w-5 text-blue-600" />
                    </div>
                    <div>
                      <CardTitle className="text-lg font-semibold text-gray-900 group-hover:text-blue-600 transition-colors">
                        {report.title}
                      </CardTitle>
                    </div>
                  </div>
                  <Badge className={getPriorityColor(report.priority)} variant="secondary">
                    {report.priority}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <p className="text-gray-600 text-sm mb-4 leading-relaxed">{report.description}</p>
                <div className="flex items-center justify-between">
                  <Badge className={getStatusColor(report.status)} variant="outline">
                    {report.status}
                  </Badge>
                  <span className="text-xs text-gray-500">Generated by AI</span>
                </div>
              </CardContent>
            </Card>
          )
        })}
      </div>

      {/* Additional AI Features Section */}
      <div className="mt-8 p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-200">
        <div className="flex items-center space-x-3 mb-4">
          <div className="p-2 bg-blue-100 rounded-lg">
            <Zap className="h-5 w-5 text-blue-600" />
          </div>
          <h3 className="text-lg font-semibold text-gray-900">AI-Powered Features</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="text-center p-4">
            <div className="text-2xl font-bold text-blue-600 mb-1">98%</div>
            <div className="text-sm text-gray-600">Matching Accuracy</div>
          </div>
          <div className="text-center p-4">
            <div className="text-2xl font-bold text-green-600 mb-1">2.5x</div>
            <div className="text-sm text-gray-600">Faster Discovery</div>
          </div>
          <div className="text-center p-4">
            <div className="text-2xl font-bold text-purple-600 mb-1">15K+</div>
            <div className="text-sm text-gray-600">Data Points Analyzed</div>
          </div>
        </div>
      </div>
    </div>
  )
}
